### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [rmtew/peasauce#9]
this looks like a very nice tool! you may want to use M68k with Capstone, which was supported in Capstone long ago.

https://github.com/aquynh/capstone/tree/next/arch

keep it up, cheers.

**Comment by rmtew** [comment]
Hi,

I've been looking at using Capstone as of yesterday, and although a nice
lightweight and easy to understand project, it's currently unsuitable.

My m68k focused users (which mostly try it out to see how it is coming
along, and are few) are not very likely to compile the "next" branch
themselves.  Are pypi packages available or possible with minimal work?
Even bleeding edge ones automatically uploaded with a daily build?

I do not know your criteria for accepting new architectures.  My project
while mostly about m68k at the moment, will later return to concentrating
on other architectures I've partially added like 65c816 (for snes) and z80
(for zxspectrum), as they are other retro-computing architectures.  Would
you accept these if contributed to Capstone, and are they within the scope
of your project?

Cheers,
Richard.











On Fri, Oct 21, 2016 at 12:49 PM, Nguyen Anh Quynh <notifications@github.com

**Comment by aquynh** [comment]
you can use this command to install Capstone binding directly from Github:

    $ sudo pip install "https://github.com/aquynh/capstone/archive/next.zip#egg=capstone&subdirectory=bindings/python"

on new architectures, yes we are happily accept pull reqs for them.

keep it up, cheers.
